# Generated by Django 5.1.7 on 2025-05-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('UserId', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
            ],
        ),
    ]
