# Generated by Django 5.1.7 on 2025-05-08 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
        ('inventari', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('ComandaId', models.AutoField(primary_key=True, serialize=False)),
                ('Quantitat', models.IntegerField()),
                ('PreuFinal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventari.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.usuari')),
            ],
        ),
    ]
