# Generated by Django 5.1.7 on 2025-05-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_comanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuari',
            name='UserId',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
