# Generated by Django 5.1.7 on 2025-05-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_usuari_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuari',
            name='Username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
