# Generated by Django 5.1.7 on 2025-05-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('CodigoArticulo', models.AutoField(primary_key=True, serialize=False)),
                ('DescripcionArticulo', models.CharField(max_length=100)),
                ('PVP', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Unidades', models.IntegerField()),
            ],
        ),
    ]
